name: catbreeds
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.8.4
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  go_router: ^14.8.1
  flutter_dotenv: ^5.2.1
  http: ^1.3.0
  url_launcher: ^6.3.1
  mocktail: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner: ^5.0.0
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/cat.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/cat.png"
  remove_alpha_ios: true
  remove_alpha_android: true
  android_adaptive_icon_background: "#ffffff"
  android_adaptive_icon_foreground: "assets/icons/cat.png"
  android_adaptive_icon_foreground_color: "#ffffff"
  android_adaptive_icon_background_color: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - .env
